### ISSUE TITLE
If it doesn't work using it with Bootstrap

### ISSUE THREAD

**Issue by fversepuy** [ryun/HCaptions#4]
Hi, 

I don't know if this is the good place for posting this, but I have a small advice if you use the example provided "as is" (and Bootstrap css) and don't see anything, no caption at all.

I spent lot of time wondering why HCaptions was not working for me. You have to remove class="hide" from the caption div, as Bootstrap already uses this class (for hiding, of course).
Hope this will save somebody's time.

Maybe it would be a good idea to change this confusing class in the example provided.

**Comment by yanismydj** [comment]
having the same problem with this myself, thanks for the tip @Fanfan92

**Comment by fversepuy** [comment]
You're welcome! I'm glad it helps.
