### ISSUE TITLE
Problem with Prestashop & cache

### ISSUE THREAD

**Issue by iecul** [ryun/HCaptions#9]
Hello,

The first time you visit a page with hcaption, le plugin not working well, but if you refresh the page, it's ok... Have you got an idea to solve it? 

![capture d ecran 2015-06-26 a 11 26 56](https://cloud.githubusercontent.com/assets/13062546/8374524/563f95c2-1bf6-11e5-9fd0-0120e798cc75.png)

**Comment by ryun** [comment]
Do you have a link to the resulting page for debugging?

**Comment by iecul** [comment]
Hello!

Thank  you for the quick reply, the link is http://www.iq-shopping.com. 
Thank you so much in advance !

Lucie

Envoyé de mon iPhone

**Comment by iecul** [comment]
Hello,

Thank you for your reply,

Here : http://www.iq-shopping.com/ http://www.iq-shopping.com/ you can see the problem after refresh all is OK. But if you refresh and emptying the cache (cmd+shift+R), the problem still here. 

Thank you for your help. 

Lucie

---

Lucie DEFORGES
Développeur Web | Freelance 
06.81.35.29.64 | Tours 37
www.luciedeforges.com
